### ISSUE TITLE
Create an installable paclet for `QuiverGeometry`

### ISSUE THREAD

**Issue by taliesinb** [taliesinb/QuiverGeometry#8]
## Problem

Non-experts can't easily install and use `QuiverGeometry`.

## Solution

Create an installable paclet, with builds. This involves solving two other issues: an installable stylesheet that doesn't require committing a notebook, and (optionally) automatically built paclet documentation.

**Comment by raverydavis** [comment]
Add to paclet repository as well: https://resources.wolframcloud.com/PacletRepository/

(Bonus: use releases so one can also do GitHubInstall from WFR: https://resources.wolframcloud.com/FunctionRepository/resources/GitHubInstall/)
